name: Liechtenstein power

on:
  push:
    branches: ["master"]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build image
        run: docker build -t oe .
      - name: Run container
        run: docker run oe
