name: Liechtenstein power

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches: ["master"]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
      - name: Build image
        run: docker build --tag oe --file processing/Dockerfile .
      - name: Andorra
        run: |
          docker run \
            -e B2_APPLICATION_KEY_ID=${{ secrets.B2_APPLICATION_KEY_ID }} \
            -e B2_APPLICATION_KEY=${{ secrets.B2_APPLICATION_KEY }} \
            oe europe/andorra
      - name: Cook Islands
        run: |
          docker run \
            -e B2_APPLICATION_KEY_ID=${{ secrets.B2_APPLICATION_KEY_ID }} \
            -e B2_APPLICATION_KEY=${{ secrets.B2_APPLICATION_KEY }} \
            oe australia-oceania/cook-islands
      - name: Liechtenstein
        run: |
          docker run \
            -e B2_APPLICATION_KEY_ID=${{ secrets.B2_APPLICATION_KEY_ID }} \
            -e B2_APPLICATION_KEY=${{ secrets.B2_APPLICATION_KEY }} \
            oe europe/liechtenstein
