name: Extraction

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches: ["master"]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
      - name: Build image
        run: docker build --tag oe --file processing/Dockerfile processing/
      - name: Iceland
        run: |
          docker run \
            --env REGION_NAME=${{ secrets.REGION_NAME }} \
            --env ENDPOINT_URL=${{ secrets.ENDPOINT_URL }} \
            --env KEY_ID=${{ secrets.KEY_ID }} \
            --env SECRET=${{ secrets.SECRET }} \
            oe europe/iceland power power
